#+TITLE: Práctica 2
#+Author: Luis Eduardo Galindo Amaya
#+email:  egalindo54@uabc.edu.mx

#+DESCRIPTION:
#+KEYWORDS: 
#+LANGUAGE: es
#+DATE: \today

#+OPTIONS: \n:t num:1 toc:nil title:nil 

#+LATEX_COMPILER: pdflatex
#+LATEX_CLASS: article
#+LATEX_CLASS_OPTIONS:
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage{svg,listings}

#+BEGIN_EXPORT latex
\begin{titlepage}
\centering
{\bfseries\LARGE Universidad Autonoma \par de Baja California \par}
\vspace{1cm}
{\scshape\Large Interacción Humano-Computadora \par}
\vspace{2cm}
{\scshape\Huge Control de versionamiento Git \par}
\vspace{2cm}
{\itshape\Large Práctica 2 \par}
\vfill
\begin{center}
\includegraphics[width=4cm]{img/logo}
\end{center}
\vfill
{\Large Autor: \par}
{\Large Luis E. Galindo Amaya \par}
{\Large 1274895 \par}
\vfill
{\Large \today \par}
\end{titlepage}
#+END_EXPORT

* Repositorio
- IHC-2022 :: https://github.com/Galindo-lab/IHC-2022

* Preguntas
** ¿Qué es Git?
Git es una herramienta que controla versiones de código de forma distribuida. Su propósito es llevar registro de los cambios en archivos de computadora incluyendo coordinar el trabajo que varias personas realizan sobre archivos compartidos en un repositorio de código.

** ¿Qué es un commit?
un commit es cuando ponemos las actualizaciones mas rercientes de un documento en la rama en la que se cuentre.

** ¿Qué es un branch?
Una rama representa una línea independiente de desarrollo. Las ramas sirven como una abstracción de los procesos de cambio, preparación y confirmación. Puedes concebirlas como una forma de solicitar un nuevo directorio de trabajo, un nuevo entorno de ensayo o un nuevo historial de proyecto

** ¿Qué es un merge?
La fusión es la forma que tiene Git de volver a unir un historial bifurcado. El comando git merge permite tomar las líneas independientes de desarrollo creadas por git branch e integrarlas en una sola rama.

** Describa el funcionamiento de fetch, pull y push.
*** git fetch
Descarga los cambios realizados en el repositorio remoto.

*** git pull
Unifica los comandos fetch y merge en un único comando.

*** git push origin <nombre_rama>:
Sube la rama “nombre_rama” al servidor remoto.

* Problema
Dado un arreglo de números enteros nums y un entero target, implementar una función que regrese los indices de dos números que sumados den como resultado el target. Asumir que siempre habrá al menos una solución, y tampoco se puede repetir el mismo elemento más de una vez. La respuesta se puede regresar en cualquier orden.

#+BEGIN_SRC 
public int[] SumaDos(int[] nums, int target) {}
Ejemplo:
Input: nums = [2,7,11,15], target = 18
Output = [1, 2]
#+END_SRC

BONUS: Indicar la complejidad en espacio y tiempo.

** Implementacion

#+BEGIN_SRC 
nums = [2,7,11,15]
target = 10


def sumaDos(nums, target):
    for i, v in enumerate(nums):
        missing = target - v
        if missing < 0: pass
        for j, w in enumerate(nums):
            if w == missing: return (i,j)
        
    
print(sumaDos(nums, target))
#+END_SRC

* Comentarios Y Conclusiones
